<a href="https://colab.research.google.com/github/sarannetworkprogammer/Ml_rad/blob/main/sep25_ML_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

x = torch.empty(1)
print(x)

tensor([2.1235e-35])


In [ ]:
# random value

x = torch.rand(2,3)
print(x)

tensor([[0.9139, 0.2763, 0.6470],
        [0.6056, 0.1839, 0.3858]])


In [ ]:
# printing ones values

x = torch.ones(3,3, dtype=torch.float16)
print(x)
print(x.dtype)
print(f"size= {x.size()}")

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
torch.float16
size= torch.Size([3, 3])


In [ ]:

#tensor
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y # z= torch.add(x,y)
print(z)

tensor([[0.6666, 0.0686],
        [0.0355, 0.9598]])
tensor([[0.7425, 0.5986],
        [0.7540, 0.1695]])
tensor([[1.4092, 0.6672],
        [0.7895, 1.1293]])


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

y.add_(x)
print(y)

tensor([[0.8331, 1.3430],
        [0.5669, 1.4498]])


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x *y 
print(z)

y.mul_(x)
print("mul=",y)
z = x

tensor([[0.2178, 0.8707],
        [0.1585, 0.2672]])
tensor([[0.5453, 0.5925],
        [0.2781, 0.5372]])
tensor([[0.1187, 0.5158],
        [0.0441, 0.1435]])
tensor([[0.1187, 0.5158],
        [0.0441, 0.1435]])


In [ ]:
x = torch.rand(5,3)
print(x)
print("\n")
print(x[:1])
print("\n")

print(x[1,1].item())

tensor([[0.2446, 0.4787, 0.5817],
        [0.4753, 0.8402, 0.4243],
        [0.1068, 0.8392, 0.1514],
        [0.0845, 0.3641, 0.4900],
        [0.5624, 0.1372, 0.3686]])


tensor([[0.2446, 0.4787, 0.5817]])


0.8402020335197449


In [ ]:
# reshaping 

x = torch.rand(4,4)
print(x)
# here number of elements should be same
y = x.view(-1,8) # it automitacllay determines the size
print(y)

tensor([[0.2579, 0.6884, 0.3307, 0.6683],
        [0.4314, 0.7887, 0.4054, 0.3964],
        [0.7692, 0.4859, 0.5411, 0.8683],
        [0.9241, 0.6324, 0.5474, 0.7575]])
tensor([[0.2579, 0.6884, 0.3307, 0.6683, 0.4314, 0.7887, 0.4054, 0.3964],
        [0.7692, 0.4859, 0.5411, 0.8683, 0.9241, 0.6324, 0.5474, 0.7575]])


In [ ]:
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))
print(b)
print("\n")
a.add_(1)
print(a)
print("b",b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]


tensor([2., 2., 2., 2., 2.])
b [2. 2. 2. 2. 2.]


In [ ]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a +=1
print(a)
print("b",b) 

# check that 

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
b tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
print(torch.cuda.is_available)
#numpy can only handle cpu tensor
# cuda tensors


<function is_available at 0x7f57cc14eef0>


In [ ]:
x = torch.ones(5,requires_grad=True) # later calculates gradient 
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [ ]:
# auto grad 

x = torch.randn(3,requires_grad=True)
print(x)

y = x + 2

print(y)

z = y*y*2

z= z.mean()
print(z)

z.backward() # dz/dx
print(x.grad)

tensor([-0.2498,  0.0807,  0.6945], requires_grad=True)
None
tensor([1.7502, 2.0807, 2.6945], grad_fn=<AddBackward0>)
tensor(9.7687, grad_fn=<MeanBackward0>)
tensor([2.3336, 2.7743, 3.5926])


In [ ]:
x = torch.randn(3,requires_grad=True)
print(x)

# x.requiresg_grad_(False)
#x.detach()
#with torch.no_Grad()

#x.requires_grad_(False)

y = x.detach()
print(y)






tensor([1.5328, 3.0035, 0.1362], requires_grad=True)
tensor([1.5328, 3.0035, 0.1362])


In [ ]:
weights = torch.ones(4,requires_grad=True)
print(weights)


for epoch in range(3):
  model_output = (weights*3).sum()
  print(model_output)
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([1., 1., 1., 1.], requires_grad=True)
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


In [ ]:
# back propagation algorithm
"""
chain rule 

dz/dx = dz/dy . dy/dx (all ar partial deriviates )
computational graph 




"""

In [6]:
import numpy as np

# f = w * x

# f = 2 * x

X = np.array([1,2,3,4], dtype=np.float32)
Y = np.array([2,4,6,8], dtype=np.float32)

print(X)
print(Y)

w =0.0

# model prediction 


def forward(X):

  return w * X


# loss == mean square error

def loss(y, y_predicted):
  return ((y_predicted - y) **2).mean()


# gradient of loss 

#MSE = 1/N *(W*X -Y)

# dj/dw = 1/N 2X(w*x- y)

def gradient(x,y,y_predicted):
  return np.dot(2*x, y_predicted - y).mean()


print(f"prediction before training :f(5)={forward(5):.3f}")


#Training 

learning_rate = 0.01
n_iter = 20

# training_loop

for epoch in range(n_iter):
  print(f"epoch ={epoch}")
  #prediction = forward pass

  y_pred = forward(X)


  #LOSS

  l = loss(Y, y_pred)

  #gradients

  dw = gradient(X,Y,y_pred)

  # update weights

  w -= learning_rate * dw

  if epoch % 2 == 0:

    print(f"epoch {epoch +1}: w = {w:.3f}, loss={l:.8f}")


print(f"prediction after training :f(5)={forward(5):.3f}")


[1. 2. 3. 4.]
[2. 4. 6. 8.]
prediction before training :f(5)=0.000
epoch =0
epoch 1: w = 1.200, loss=30.00000000
epoch =1
epoch =2
epoch 3: w = 1.872, loss=0.76800019
epoch =3
epoch =4
epoch 5: w = 1.980, loss=0.01966083
epoch =5
epoch =6
epoch 7: w = 1.997, loss=0.00050331
epoch =7
epoch =8
epoch 9: w = 1.999, loss=0.00001288
epoch =9
epoch =10
epoch 11: w = 2.000, loss=0.00000033
epoch =11
epoch =12
epoch 13: w = 2.000, loss=0.00000001
epoch =13
epoch =14
epoch 15: w = 2.000, loss=0.00000000
epoch =15
epoch =16
epoch 17: w = 2.000, loss=0.00000000
epoch =17
epoch =18
epoch 19: w = 2.000, loss=0.00000000
epoch =19
prediction after training :f(5)=10.000
