<a href="https://colab.research.google.com/github/sarannetworkprogammer/Ml_rad/blob/main/Softmax_%26_Cross_Entropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

softmax and  cross entropy *italicized text*


softmax normalize the values 

converts all the values in between 0 and l (which is nothing but probabilities

in pytorch cross entro

no need to apply softmax at the end in torch


for cla
---



---





---



---



In [18]:
import torch
import torch.nn as nn
import numpy as np

In [19]:
loss = nn.CrossEntropyLoss()

In [20]:
Y = torch.tensor([0])
print(Y)

Y_pred_good = torch.tensor([[2.0,1.0,0.1]])
Y_pred_bad = torch.tensor([[0.5,2.0,0.3]])


l1 = loss(Y_pred_good, Y)  # FUNCTION 
l2 = loss(Y_pred_bad, Y)

print(l1)
print(l1.item())
print(l2)
print(l2.item())


_, predictions1 = torch.max(Y_pred_good,1)
_, predictions2 = torch.max(Y_pred_bad, 1)

print(predictions1)
print(predictions2)



tensor([0])
tensor(0.4170)
0.4170299470424652
tensor(1.8406)
1.840616226196289
tensor([0])
tensor([1])


In [25]:
# softmax using numpy


def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=0)

x = np.array([2.0,1.0,0.1])


outputs = softmax(x)

print("softmax numpy ", outputs)


x = torch.tensor([2.0,1.0,0.1])
outputs = torch.softmax(x,dim=0)
print(outputs)

softmax numpy  [0.65900114 0.24243297 0.09856589]
tensor([0.6590, 0.2424, 0.0986])
